export const ADD_TO_CART = 'ADD_TO_CART';
export const ON_CHANGE_MESSAGE = 'ON_CHANGE_MESSAGE';
export const ON_UPDATE_MESSAGE = 'ON_CHANGE_MESSAGE';
export const ON_DELETE_PRODUCT_IN_CART = 'ON_DELETE_PRODUCT_IN_CART';
export const ON_UPDATE_PRODUCT_IN_CART = 'ON_UPDATE_PRODUCT_IN_CART';




